import { useApiGet } from '../../hooks/useApi.js';

interface Scorecard {
  id: string;
  operatorId: string;
  reportingPeriodStart: string;
  reportingPeriodEnd: string;
  generatedAt: string;
  metricsSnapshot: Record<string, unknown>;
}

export default function ShipperScorecards() {
  const { data, error, loading } = useApiGet<Scorecard[]>('/shipper/scorecards');

  return (
    <div>
      <h1>Scorecards</h1>
      <div className="subtitle">Weekly reliability scorecards generated by your operators.</div>
      {error && <div className="error-banner">{error}</div>}
      {loading && <div className="empty-state">Loading...</div>}
      <div className="card">
        {data && data.length === 0 && <div className="empty-state">No scorecards generated yet.</div>}
        {data?.map((s) => (
          <div key={s.id} style={{ marginBottom: 18 }}>
            <strong>{s.reportingPeriodStart} – {s.reportingPeriodEnd}</strong>
            <table>
              <tbody>
                {Object.entries(s.metricsSnapshot).filter(([k]) => k !== 'sampleSize').map(([k, v]) => (
                  <tr key={k}><td style={{ textTransform: 'capitalize' }}>{k.replace(/([A-Z])/g, ' $1')}</td><td>{String(v)}</td></tr>
                ))}
              </tbody>
            </table>
          </div>
        ))}
      </div>
    </div>
  );
}
